"""Quantum ESPRESSO interface for importing phonon data."""

import numpy as np
from . import unit2


def reader_dyn(filename):
    """Read dyn file generated by QE: force constants, Born charges, masses."""
    amu_ryd = unit2.amu_ryd
    bohr = unit2.Bohr2A
    dynunit_qeh2qe = unit2.hbar**2 *1e20 /unit2.e_charge /unit2.amu \
        /unit2.ry2ev**2  *unit2.amu_ryd

    def search_patt(p, l):
        return [s.strip() for s in l].index(p)

    with open(filename, 'r') as fo:
        lines = fo.readlines()

    ntype, natm = int(lines[2].split()[0]), int(lines[2].split()[1])
    tp_mass = np.array([float(lines[3+i].split()[-1]) for i in range(ntype)])
    tp_mass = tp_mass/amu_ryd

    at_tp = [int(lines[3+ntype+i].split()[1])-1 for i in range(natm)]
    at_mass = np.array([tp_mass[i] for i in at_tp])

    tp_syb = np.array([lines[3+i][15:17] for i in range(ntype)], dtype='<U2')
    at_syb = np.array([tp_syb[i] for i in at_tp], dtype='<U2')

    ibrav = int(lines[2].split()[2])
    celldm = np.array([float(entry) for entry in lines[2].split()[3:9]])
    if ibrav == 4:
        cell = np.array([[celldm[0], 0, 0],
                        [-0.5*celldm[0], celldm[0]*3**0.5/2, 0],
                        [0, 0, celldm[0]*celldm[2]]])
        cell = cell * bohr

    dynheader = search_patt('Dynamical  Matrix in cartesian axes', lines)
    dynabij = np.zeros((natm, natm, 3, 3))
    dynmn = np.zeros((3*natm, 3*natm))

    di = dynheader + 5
    for a in range(natm):
        for b in range(natm):
            for i in [0,1,2]:
                dynabij[a,b,i] = [float(lines[di].split()[i]) for i in [0,2,4]]
                di += 1
                for j in [0,1,2]:
                    dynmn[3*a+i, 3*b+j] = dynabij[a,b,i,j]
            di += 1

    dynabij = dynabij / dynunit_qeh2qe
    dynmn = dynmn / dynunit_qeh2qe

    Zheader = search_patt("Effective Charges E-U: Z_{alpha}{s,beta}", lines)
    Zaij = np.zeros((natm, 3, 3))

    zi = Zheader + 3
    for a in range(natm):
        for i in [0,1,2]:
            Zaij[a,i] = [float(lines[zi].split()[i]) for i in [0,1,2]]
            zi += 1
        zi += 1

    return at_mass, dynmn, Zaij, at_syb, cell


def replace_phonons(bbname, qedata, BCx=1.0, FCpow=0.0):
    bb = np.load(bbname)

    at_mass, dyn, Zaij, _, _ = qedata
    print(Zaij)
    print('QEH:')
    print(bb['masses'])
    print('qe:')
    print(at_mass)

    symbols = bb['symbols']
    cell = bb['cell']
    save_phonons(bbname, (at_mass, dyn, Zaij), symbols, cell, BCx=BCx, FCpow=FCpow)


def save_phonons(bbname, qedata, symbols, cell, BCx=1.0, FCpow=0.0):
    bb = dict()

    at_mass, dyn, Zaij = qedata

    bb['Z_avv'] = Zaij * BCx
    bb['C_NN'] = dyn / 2**(0.5*FCpow)
    bb['masses'] = at_mass
    bb['symbols'] = symbols
    bb['cell'] = cell

    np.savez_compressed(bbname, **bb)


def dyn_qe2qeh(dynfile, bbname, restart=True, BCx=1.0, FCpow=0.0):
    """Convert QE .dyn file to qeh phonon .npz format."""
    qedata = reader_dyn(dynfile)
    if restart:
        replace_phonons(bbname, qedata, BCx=BCx, FCpow=FCpow)
    else:
        save_phonons(bbname, qedata[0:3], qedata[3], qedata[4], BCx=BCx, FCpow=FCpow)
